"""Account Delete should CASCADE to accountshare and SET NULL to transaction

Revision ID: 3c1d269eb073
Revises: 
Create Date: 2026-01-26 18:04:54.240155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c1d269eb073'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Make transaction.account_id nullable first
    op.alter_column('transaction', 'account_id',
               existing_type=sa.UUID(),
               nullable=True)

    # Drop and recreate accountshare foreign key with CASCADE
    op.drop_constraint('accountshare_account_id_fkey', 'accountshare', type_='foreignkey')
    op.create_foreign_key('accountshare_account_id_fkey', 'accountshare', 'account', ['account_id'], ['id'], ondelete='CASCADE')

    # Drop and recreate transaction foreign key with SET NULL
    op.drop_constraint('transaction_account_id_fkey', 'transaction', type_='foreignkey')
    op.create_foreign_key('transaction_account_id_fkey', 'transaction', 'account', ['account_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverse operations for rollback safety
    # Drop and recreate foreign keys without ondelete clauses
    op.drop_constraint('transaction_account_id_fkey', 'transaction', type_='foreignkey')
    op.create_foreign_key('transaction_account_id_fkey', 'transaction', 'account', ['account_id'], ['id'])

    op.drop_constraint('accountshare_account_id_fkey', 'accountshare', type_='foreignkey')
    op.create_foreign_key('accountshare_account_id_fkey', 'accountshare', 'account', ['account_id'], ['id'])

    # Make transaction.account_id non-nullable again
    op.alter_column('transaction', 'account_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
