# pytest configuration file
# -v (verbose) shows each test as it runs with PASSED/FAILED/...
# You can add more options here, e.g. -q, -k, -r a, etc.
[pytest]
addopts = -v
testpaths = backend/api/tests
asyncio_mode = auto
