# backend/api/app/models.py
from __future__ import annotations

from typing import Optional
from uuid import UUID, uuid4
from datetime import datetime, date
from decimal import Decimal
from enum import Enum

from sqlmodel import SQLModel, Field
from sqlalchemy import Column, Enum as SAEnum, Numeric, UniqueConstraint, ForeignKey, String
from sqlalchemy.dialects.postgresql import UUID as PGUUID

# --------------------
# Python enums
# --------------------
class CategoryKind(str, Enum):
    """Kind of category indicating whether it represents an expense or income.

    Used to classify categories and transactions as either costs (expense)
    or earnings (income).
    """
    EXPENSE = "expense"
    INCOME = "income"

class TransactionSource(str, Enum):
    """Source of a transaction describing how it was created.

    MANUAL: created by a user interaction.
    RECURRING: generated by a scheduled/recurring process.
    """
    MANUAL = "manual"
    RECURRING = "recurring"

# TransactionType is the same as CategoryKind (alias)
TransactionType = CategoryKind

class MembershipRole(str, Enum):
    """Role assigned to a membership within a tenant.

    OWNER has full control, MEMBER has standard access, VIEWER has read-only access.
    """
    OWNER = "owner"
    MEMBER = "member"
    VIEWER = "viewer"

class MembershipStatus(str, Enum):
    """Lifecycle status for a membership or invite.

    ACTIVE: membership is active and usable.
    PENDING: invite sent or awaiting acceptance.
    REVOKED: membership or invite has been revoked.
    """
    ACTIVE = "active"
    PENDING = "pending"
    REVOKED = "revoked"

class AccountType(str, Enum):
    """Type of a financial account, affecting expected behavior and balance handling.

    CASH: cash-like accounts, DEBIT: bank/debit accounts, CREDIT: credit card accounts.
    """
    CASH = "cash"
    DEBIT = "debit"
    CREDIT = "credit"

class Currency(str, Enum):
    """Supported currency codes used for monetary fields across the models."""
    BRL = "BRL"
    USD = "USD"
    EUR = "EUR"

class ShareVisibility(str, Enum):
    """Controls whether an account's balance is visible to a membership."""
    HIDDEN = "hidden"
    VISIBLE = "visible"

class ImportJobStatus(str, Enum):
    """Lifecycle status for a CSV import job.

    PENDING: row inserted by the API, not yet picked up by a worker.
    STARTED: the worker has begun processing the rows.
    DONE: all rows committed successfully.
    FAILED: the worker raised an exception; error_message holds the reason.
    """
    PENDING = "pending"
    STARTED = "started"
    DONE = "done"
    FAILED = "failed"

# --------------------
# Models
# --------------------
class User(SQLModel, table=True):
    """Represents an application user.

    Attributes:
        id: Unique identifier for the user.
        email: Login email address (indexed).
        password_hash: Hashed password for authentication.
        name: Optional display name.
        created_at: Timestamp when the user was created.
        language: Preferred UI language as a BCP-47 code ("en" or "pt-BR").
    """
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    email: str = Field(nullable=False, index=True)
    password_hash: str
    name: Optional[str] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    preferred_tenant_id: Optional[UUID] = Field(default=None, nullable=True, index=True)
    # Preferred UI language as a BCP-47 code ("en" or "pt-BR"). Stored on the user
    # (not the tenant) because language is a personal preference that should follow
    # the user across every family they belong to and across devices. Non-nullable
    # with a default of English; the migration backfills existing rows via
    # server_default so no data migration is required.
    language: str = Field(default="en", nullable=False)

class Tenant(SQLModel, table=True):
    """Represents a Family (tenant) that groups data and users.

    Attributes:
        id: Unique tenant identifier.
        name: Human-readable tenant name.
        created_at: Timestamp when the tenant was created.
    """
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    name: str
    created_at: datetime = Field(default_factory=datetime.utcnow)

class Membership(SQLModel, table=True):
    """Association between a user (or invite) and a family (tennat).

    A membership links a user (or an invite email) to a tenant and assigns a role
    and status.

    Attributes:
        tenant_id: The tenant this membership belongs to.
        user_id: Optional user id; null for pending invites.
        user_email: Email used for invite flow when user_id is not set.
        role: Role of the membership (OWNER/MEMBER/VIEWER).
        status: Current membership status.
    """
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    tenant_id: UUID = Field(
        sa_column=Column(
            PGUUID(as_uuid=True),
            ForeignKey("tenant.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        )
    )
    user_id: Optional[UUID] = Field(foreign_key="user.id", nullable=True, index=True)  # null for pending invites
    user_email: Optional[str] = Field(default=None, index=True)  # invite flow
    role: MembershipRole = Field(
        sa_column=Column(SAEnum(MembershipRole, name="membership_role"), nullable=False),
        default=MembershipRole.MEMBER,
    )
    status: MembershipStatus = Field(
        sa_column=Column(SAEnum(MembershipStatus, name="membership_status"), nullable=False),
        default=MembershipStatus.ACTIVE,
    )
    created_at: datetime = Field(default_factory=datetime.utcnow)

class Account(SQLModel, table=True):
    """A financial account owned by a user.

    Attributes:
        id: Unique account identifier.
        user_id: Owner user identifier.
        name: Account display name.
        type: Type of account (cash/debit/credit).
        currency: Account currency code.
        balance: Current numeric balance.
        created_at: Creation timestamp.
        updated_at: Last update timestamp.
    """
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    user_id: UUID = Field(foreign_key="user.id", nullable=False, index=True)
    name: str
    type: AccountType = Field(
        sa_column=Column(SAEnum(AccountType, name="account_type"), nullable=False),
        default=AccountType.CASH,
    )
    currency: Currency = Field(
        sa_column=Column(SAEnum(Currency, name="account_currency"), nullable=False),
        default=Currency.BRL,
    )
    balance: Decimal = Field(
        default=Decimal("0.00"),
        sa_column=Column(Numeric(18, 2), nullable=False),
    )
    icon: Optional[str] = Field(default=None, sa_column=Column(String(64), nullable=True))
    color: Optional[str] = Field(default=None, sa_column=Column(String(7), nullable=True))
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

class Category(SQLModel, table=True):
    """Category used to classify transactions within a tenant.

    Attributes:
        id: Category identifier.
        tenant_id: Tenant this category belongs to.
        name: Category name.
        parent_id: Optional parent category for hierarchical categorization.
        kind: Whether the category is an expense or income.
    """
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    tenant_id: UUID = Field(
        sa_column=Column(
            PGUUID(as_uuid=True),
            ForeignKey("tenant.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        )
    )
    name: str
    parent_id: Optional[UUID] = Field(default=None, foreign_key="category.id")
    kind: CategoryKind = Field(
        sa_column=Column(SAEnum(CategoryKind, name="category_kind"), nullable=False),
    )
    icon: Optional[str] = Field(default=None, sa_column=Column(String(64), nullable=True))
    color: Optional[str] = Field(default=None, sa_column=Column(String(7), nullable=True))
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

class Transaction(SQLModel, table=True):
    """Represents a financial transaction recorded against an account.

    Attributes:
        id: Transaction identifier.
        tenant_id: Tenant context for multi-tenant isolation.
        account_id: Account associated with the transaction.
        category_id: Optional category classification.
        transaction_date: Date when the transaction occurred.
        transaction_type: Expense or income.
        amount: Monetary amount of the transaction.
        currency: Currency code for the amount.
        created_by: User who created the transaction.
        description: Optional free-text description.
        reconciled: Whether the transaction has been reconciled.
        source: Origin of the transaction (manual/recurring).
    """
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    tenant_id: UUID = Field(
        sa_column=Column(
            PGUUID(as_uuid=True),
            ForeignKey("tenant.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        )
    )
    account_id: Optional[UUID] = Field(
        default=None,
        sa_column=Column(PGUUID(as_uuid=True), ForeignKey("account.id", ondelete="SET NULL"), nullable=True, index=True)
    )
    category_id: Optional[UUID] = Field(default=None, foreign_key="category.id", index=True)

    transaction_date: date = Field(nullable=False)
    transaction_type: TransactionType = Field(
        sa_column=Column(SAEnum(CategoryKind, name="transaction_type"), nullable=False),
        default=TransactionType.EXPENSE,
    )

    amount: Decimal = Field(sa_column=Column(Numeric(18, 2), nullable=False))
    currency: Currency = Field(
        sa_column=Column(SAEnum(Currency, name="transaction_currency"), nullable=False),
        default=Currency.BRL,
    )
    created_by: UUID = Field(foreign_key="user.id", nullable=False, index=True)

    description: Optional[str] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    reconciled: bool = Field(default=False)
    source: TransactionSource = Field(
        sa_column=Column(SAEnum(TransactionSource, name="transaction_source"), nullable=False),
        default=TransactionSource.MANUAL,
    )

class AccountShare(SQLModel, table=True):
    """
    Links an account to a tenant (family). Controls visibility of balance (HIDDEN / VISIBLE)
    for members of the grantee tenant.
    """
    __table_args__ = (
        UniqueConstraint("account_id", "tenant_id", name="uq_account_share_account_tenant"),
    )

    id: UUID = Field(default_factory=uuid4, primary_key=True)
    account_id: UUID = Field(
        sa_column=Column(PGUUID(as_uuid=True), ForeignKey("account.id", ondelete="CASCADE"), nullable=False, index=True)
    )
    tenant_id: UUID = Field(
        sa_column=Column(
            PGUUID(as_uuid=True),
            ForeignKey("tenant.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        )
    )
    visibility: ShareVisibility = Field(
        sa_column=Column(SAEnum(ShareVisibility, name="share_visibility"), nullable=False),
        default=ShareVisibility.HIDDEN,
    )
    granted_by: UUID = Field(foreign_key="user.id", nullable=False, index=True)
    granted_at: datetime = Field(default_factory=datetime.utcnow)
class Budget(SQLModel, table=True):
    """Represents a monthly spending budget scoped to a tenant.

    A budget defines a spending limit (amount) for a given set of categories.
    When no categories are linked, the budget tracks ALL tenant expense
    transactions (universal budget). Categories are linked via the
    BudgetCategory join table.

    Attributes:
        id: Unique budget identifier.
        tenant_id: Tenant this budget belongs to (multi-tenant isolation).
        name: Human-readable budget name (e.g. "Monthly Entertainment").
        amount: Maximum spending limit for the budget period.
        currency: Currency code for the budget amount, must match transaction
                  currencies to correctly calculate spent totals.
        created_at: Timestamp when the budget was created.
        updated_at: Timestamp when the budget was last modified.
    """
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    tenant_id: UUID = Field(
        sa_column=Column(
            PGUUID(as_uuid=True),
            ForeignKey("tenant.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        )
    )
    name: str
    amount: Decimal = Field(sa_column=Column(Numeric(18, 2), nullable=False))
    currency: Currency = Field(
        sa_column=Column(SAEnum(Currency, name="account_currency", create_constraint=False), nullable=False),
        default=Currency.BRL,
    )
    icon: Optional[str] = Field(default=None, sa_column=Column(String(64), nullable=True))
    color: Optional[str] = Field(default=None, sa_column=Column(String(7), nullable=True))
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)


class BudgetCategory(SQLModel, table=True):
    """Join table linking budgets to categories (many-to-many).

    Each row associates one budget with one category. The unique constraint
    on (budget_id, category_id) prevents duplicate associations. The tenant_id
    column is required per the north_star invariant that every domain record
    must include a valid tenant_id for multi-tenant isolation.

    Attributes:
        id: Unique row identifier.
        tenant_id: Tenant this association belongs to.
        budget_id: The budget being linked.
        category_id: The category being linked.
        added_at: Timestamp when the association was created.
    """
    __tablename__ = "budgetcategory"
    __table_args__ = (
        UniqueConstraint("budget_id", "category_id", name="uq_budget_category_budget_category"),
    )

    id: UUID = Field(default_factory=uuid4, primary_key=True)
    tenant_id: UUID = Field(
        sa_column=Column(
            PGUUID(as_uuid=True),
            ForeignKey("tenant.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        )
    )
    budget_id: UUID = Field(
        sa_column=Column(
            PGUUID(as_uuid=True),
            ForeignKey("budget.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        )
    )
    category_id: UUID = Field(
        sa_column=Column(
            PGUUID(as_uuid=True),
            ForeignKey("category.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        )
    )
    added_at: datetime = Field(default_factory=datetime.utcnow)


class RefreshToken(SQLModel, table=True):
    """Opaque refresh token stored hashed for long-lived session management.

    Attributes:
        id: Unique refresh token identifier (server-side).
        user_id: Owner user identifier.
        token_hash: Hashed opaque token value stored securely.
        issued_at: When the token was issued.
        expires_at: Expiration timestamp for the token.
        revoked: Whether the token has been revoked.
        device_info: Optional device description for the token.
    """
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    user_id: UUID = Field(foreign_key="user.id", nullable=False, index=True)
    token_hash: str
    issued_at: datetime = Field(default_factory=datetime.utcnow)
    expires_at: datetime
    revoked: bool = Field(default=False)
    device_info: Optional[str] = None

class ImportJob(SQLModel, table=True):
    """Persistent record of a CSV import job dispatched to the background worker.

    The API creates this row in PENDING state before dispatching the Celery task.
    The worker updates it to STARTED on entry, then DONE or FAILED on exit. This
    gives users a queryable history of past imports independent of Celery's
    transient result backend.

    Attributes:
        id: ImportJob identifier (also passed to the worker in the task payload).
        tenant_id: Tenant context for multi-tenant isolation.
        account_id: Account the rows were imported into.
        created_by: User who triggered the import.
        file_key: Storage key of the uploaded CSV (deleted after success).
        filename: Original filename as uploaded by the user, for display.
        total_rows: Number of rows the user confirmed for import.
        imported_rows: Number actually committed (equals total_rows on DONE).
        status: Lifecycle status (PENDING/STARTED/DONE/FAILED).
        error_message: Failure reason when status is FAILED.
        celery_task_id: Celery task identifier returned at dispatch time.
        created_at: When the API created this record.
        updated_at: Last status transition timestamp.
        completed_at: When the worker reached a terminal state (DONE or FAILED).
    """
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    tenant_id: UUID = Field(
        sa_column=Column(
            PGUUID(as_uuid=True),
            ForeignKey("tenant.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        )
    )
    account_id: UUID = Field(
        sa_column=Column(
            PGUUID(as_uuid=True),
            ForeignKey("account.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        )
    )
    created_by: UUID = Field(foreign_key="user.id", nullable=False, index=True)
    file_key: str = Field(nullable=False)
    filename: Optional[str] = None
    total_rows: int = Field(nullable=False, default=0)
    imported_rows: int = Field(nullable=False, default=0)
    status: ImportJobStatus = Field(
        sa_column=Column(SAEnum(ImportJobStatus, name="import_job_status"), nullable=False),
        default=ImportJobStatus.PENDING,
    )
    error_message: Optional[str] = None
    celery_task_id: Optional[str] = Field(default=None, index=True)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    completed_at: Optional[datetime] = None


class Invite(SQLModel, table=True):
    """Represents an outstanding invite to join a tenant.

    Attributes:
        id: Invite identifier.
        tenant_id: Tenant the invite applies to.
        email: Email address invited.
        token_hash: Hashed invite token used to validate acceptance.
        role: Role assigned upon acceptance.
        expires_at: When the invite expires.
        consumed: Whether the invite token has been used.
    """
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    tenant_id: UUID = Field(
        sa_column=Column(
            PGUUID(as_uuid=True),
            ForeignKey("tenant.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        )
    )
    email: str
    token_hash: str
    role: MembershipRole = Field(
        sa_column=Column(SAEnum(MembershipRole, name="invite_role"), nullable=False),
        default=MembershipRole.MEMBER,
    )
    expires_at: datetime
    consumed: bool = Field(default=False)
    created_at: datetime = Field(default_factory=datetime.utcnow)
